### ISSUE TITLE
支持折叠区域

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#10]
折叠区域，示例帖子tid：23362790
```html
<br/>感觉自己有种“姐系”的气质，举些例子：<br/>[collapse=和认识的仅有几个男生相处]<br/>实验室坐我旁边的男A：.......[del]人生三大错觉[/del]，现在已经异地实习去了<br/><br/>[/collapse]<br/><br/>
```
按发帖时的用法提示：
```
[collapse=提要]
隐藏的内容……
[/collapse]

[collapse]
没有提要也可以……
[/collapse]
```

Markdown的
```html
<details><summary>
```
标签应该是可以用的

**Comment by ludoux** [comment]
好的，努努力下次一起修掉😂

发件人: crella6<mailto:notifications@github.com>
发送时间: 2020年9月18日 22:25
收件人: ludoux/ngapost2md<mailto:ngapost2md@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [ludoux/ngapost2md] 支持折叠区域 (#10)


示例帖子tid：23362790

<br/>感觉自己有种“姐系”的气质，举些例子：<br/>[collapse=和认识的仅有几个男生相处]<br/>实验室坐我旁边的男A：.......[del]人生三大错觉[/del]，现在已经异地实习去了<br/><br/>[/collapse]<br/><br/>

Markdown的
标签应该是可以用的
