### ISSUE TITLE
利用回帖的reply_to键值来查看/跳转被回复楼

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#12]
今天见到两次带有reply_to键值的回帖的显示效果有些异常，其中一个帖子被封了，现在只发另一个：pid=454945232是tid=23362790帖子的第179楼。

![086RBt.jpg](https://s1.ax1x.com/2020/10/04/086RBt.jpg)

---

![086WHP.jpg](https://s1.ax1x.com/2020/10/04/086WHP.jpg)
该回帖的xml源码，可见content里没有“要相信缘分这东西”，但reply_to键值指向的pid=454943638就有“缘分”：
![086cjA.jpg](https://s1.ax1x.com/2020/10/04/086cjA.jpg)

**提这个issue的原因是想在离线文件里看到如图2的能看到被回复楼的效果**，我比较懒，只加了个跳转到被回复楼的链接。

这是我做的html版的效果，此时鼠标悬浮在177数字上。
![0862nI.jpg](https://s1.ax1x.com/2020/10/04/0862nI.jpg)

注：reply_to的值pid对应的楼层可能会被删除，写入文件前应先检验是否有对应pid的楼层。

**Comment by crella6** [comment]
注：nga格式化bbcode的代码好像有在不断改动。有时候能看到图2那样被回复楼的详情，有时却只能看到reply to的代码块却看不到其详情。

**Comment by crella6** [comment]
另一个参考 tid23594695_pid457017268，被回复楼pid=457013527，内容敏感，已打码
![tid23594695](https://s1.ax1x.com/2020/10/04/0GIFmD.jpg)

---

![xml](https://s1.ax1x.com/2020/10/04/0GIPOO.jpg)

**Comment by ludoux** [comment]
#### b5e5229
每一层的标题会加一个类似 `<span id="pid1234679">` 的标签，对于主楼将会是 `<span id="pid0">` 。在对应的reply、quote时候会有一个 `[jump](#pid123456)` 的跳转文本在最前面。
![圖片](https://user-images.githubusercontent.com/13460812/95970201-41d46100-0e42-11eb-8c06-619b2b2c82c0.png)

#### d7b0ab3
针对 `reply` 标签（因为好像 `quote` 正常情况下会带上原文的，btw 不是用*回帖的reply_to键值*），会在当前楼的最后有如下的一个追加，倘若回复了多个楼，会追加多个。**这个仅对此次获取的楼层生效，假如 reply 是上次获取的楼层的话，就会反显说要全新下载一次**
![圖片](https://user-images.githubusercontent.com/13460812/95970633-c45d2080-0e42-11eb-9e78-e1ca669c1b49.png)
