### ISSUE TITLE
建议:使用&lite=js或&lite=xml功能

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#2]
nga网页版支持的以下形式:
https://bbs.nga.cn/read.php?tid=21285198&lite=js => 对应json
https://bbs.nga.cn/read.php?tid=21285198&lite=xml

**Comment by ludoux** [comment]
哇！谢谢！我之后研究研究这个
________________________________

**Comment by ludoux** [comment]
谢谢你！新版本已经用新接口了。
