### ISSUE TITLE
只看作者的帖子该咋保存？

### ISSUE THREAD

**Issue by NetJim** [ludoux/ngapost2md#26]
我刚设置了authorid，但好像page会无限增大，有啥解决方法吗

**Comment by ludoux** [comment]
简单看了一下，page不增大（及认为到达的末尾）的条件判断是81行（返回True认为没结束，154行页数加）。但是问题是尽管加了只看楼主，但是返回数据中replies字段值仍然是原帖的所有回复数，就会导致一直尝试不断翻页。

最好的解决方法便是找到网页前端（或者开源版）怎么精准判断出是否到达最后一页，或者总共有多少页的方法。

比较粗糙的解决方法是可以强制加一个翻页上线，翻页尝试多少次后就终止。
________________________________
From: 王鉴 ***@***.***>
Sent: Thursday, July 15, 2021 9:17:01 PM
To: ludoux/ngapost2md ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ludoux/ngapost2md] 只看作者的帖子该咋保存？ (#26)


我刚设置了authorid，但好像page会无限增大，有啥解决方法吗

―

**Comment by NetJim** [comment]
试了用翻页成功解决了。。顺便想问下，ngaPassportCid这个是在哪找呢。。谢谢~

**Comment by ludoux** [comment]
***@***.***D77BFD.C242D0A0]登录后按F12打开开发者面板，切换到网络Tab，刷新页面，查看相应的网络请求中的**请求Cookie**字段即可。

发件人: ***@***.***>
发送时间: 2021年7月18日 17:49
收件人: ***@***.***>
抄送: Lu ***@***.***>; ***@***.***>
主题: Re: [ludoux/ngapost2md] 只看作者的帖子该咋保存？ (#26)


试了用翻页成功解决了。。顺便想问下，ngaPassportCid这个是在哪找呢。。谢谢~

―
