### ISSUE TITLE
功能缺失：无法抓取只在附件里显示的图片

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#29]
https://bbs.nga.cn/read.php?tid=28180687，楼主的图片只在json的"attachs"的"attach_url"里显示

**Comment by ludoux** [comment]
这个确实🤣最开始就发现了，但想着比较少见，就一直没有更新。（主要是之前有移植到 Go 的想法，大体移植好了，但还有小毛病，结果就一直咕咕了🤣
________________________________
From: crella6 ***@***.***>
Sent: Sunday, August 22, 2021 9:21:45 PM
To: ludoux/ngapost2md ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ludoux/ngapost2md] 功能缺失：无法抓取只在附件里显示的图片 (#29)


https://bbs.nga.cn/read.php?tid=28180687，楼主的图片只在json的"attachs"的"attach_url"里显示<https://bbs.nga.cn/read.php?tid=28180687%EF%BC%8C%E6%A5%BC%E4%B8%BB%E7%9A%84%E5%9B%BE%E7%89%87%E5%8F%AA%E5%9C%A8json%E7%9A%84%22attachs%22%E7%9A%84%22attach_url%22%E9%87%8C%E6%98%BE%E7%A4%BA>
