### ISSUE TITLE
论坛支持quote回复格式化嵌套的

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#33]
https://bbs.nga.cn/read.php?tid=29867028&page=4 74楼  嵌套quote

**Comment by ludoux** [comment]
```
[quote][pid=573856402,29867028,1]Reply[/pid] [b]Post by [uid=35188092]窝螺噗通一声[/uid] (2021-12-16 01:09):[/b]

[quote][pid=573852675,29867028,1]Reply[/pid] [b]Post by [uid=62972210]PSY-DUCK[/uid] (2021-12-16 00:44):[/b]<br/><br/>话说感觉10年前就是这些人特别火，现在欧美也没有几个新人能盖过泰勒啥的风头啊？现在不怎么听欧美歌，有没有人说一下现在谁比较火？碧梨好像算一个[/quote]<br/><br/>阿呆，A妹，黄老板，盆栽，比伯，啪姐[/quote]啪姐是真的顶[s:ac:喘]
```

![圖片](https://user-images.githubusercontent.com/13460812/147396535-58080bb8-4aaf-49a2-91ca-db46ca2a226c.png)

```
[quote][pid=573852675,29867028,1]Reply[/pid] [b]Post by [uid=62972210]PSY-DUCK[/uid] (2021-12-16 00:44):[/b]

话说感觉10年前就是这些人特别火，现在欧美也没有几个新人能盖过泰勒啥的风头啊？现在不怎么听欧美歌，有没有人说一下现在谁比较火？碧梨好像算一个[/quote]

阿呆，A妹，黄老板，盆栽，比伯，啪姐
```

**Comment by crella6** [comment]
每次rindex搜索[quote]得到坐标，然后从这个坐标index搜索[/quote]，然后替换这个片段

**Comment by ludoux** [comment]
### 新版本效果

![圖片](https://user-images.githubusercontent.com/13460812/153741777-5725dfd0-56b9-4fe7-83c7-a92c1c58ae90.png)

##### <span id="pid573910692">74.[0] \<pid:573910692\> 2021-12-16 10:10 by 欧内的手哈嘉嘉zZ</span>
>[jump](#pid573856402) 窝螺噗通一声(2021-12-16 01:09) said:
>
>>[jump](#pid573852675) PSY-DUCK(2021-12-16 00:44) said:&lt;br/&gt;&lt;br/&gt;话说感觉10年前就是这些人特别火，现在欧美也没有几个新人能盖过泰勒啥的风头啊？现在不怎么听欧美歌，有没有人说一下现在谁比较火？碧梨好像算一个
>
>&lt;br/&gt;&lt;br/&gt;阿呆，A妹，黄老板，盆栽，比伯，啪姐

啪姐是真的顶![喘](https://img4.nga.178.com/ngabbs/post/smile/ac17.png)

```
##### <span id="pid573910692">74.[0] \<pid:573910692\> 2021-12-16 10:10 by 欧内的手哈嘉嘉zZ</span>
>[jump](#pid573856402) 窝螺噗通一声(2021-12-16 01:09) said:
>
>>[jump](#pid573852675) PSY-DUCK(2021-12-16 00:44) said:&lt;br/&gt;&lt;br/&gt;话说感觉10年前就是这些人特别火，现在欧美也没有几个新人能盖过泰勒啥的风头啊？现在不怎么听欧美歌，有没有人说一下现在谁比较火？碧梨好像算一个
>
>&lt;br/&gt;&lt;br/&gt;阿呆，A妹，黄老板，盆栽，比伯，啪姐

啪姐是真的顶![喘](https://img4.nga.178.com/ngabbs/post/smile/ac17.png)
```
