### ISSUE TITLE
reply to回复块不会在bbscode里插入被回复的内容

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#35]
[提醒-功能变化]
2022-3-2，查看nga网页版帖子任意带有reply to的框块，其bbscode里不会含有被回复的内容，所以显示被回复的内容应该是网页javascript解析

**Comment by ludoux** [comment]
https://github.com/ludoux/ngapost2md/blob/218d1ca1f007d0c1c0d1998a3102f6e047ff3f2c/nga_format.py#L352

确实，现在脚本是有一个.md文档内部的跳转链接到指定的楼层。是想在输出的时候也把Reply原始楼层内容输出出来么。不过脚本设计的时候是针对每一层来format，难度可能有点大🤣

**Comment by ludoux** [comment]
**新NEO版目前已支持，但是要求线程数开到1，否则可能会出现没有format 的情况。后期看要不要修这个。以及此功能可能会放配置文件里头默认不开启，可选开启**

-----

## 默认-未开启此功能的情况 `enhance_ori_reply=False`
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/5bd02d9e-6dd8-4006-93d2-5320be7d268d)

## 开启此功能的情况 `enhance_ori_reply=True`

请注意 `thread` 需要设定为 `1`，否则有几率出现文末的异常
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/7bafb776-8180-460b-8a3c-8b7997c9c051)
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/875b77ce-c5a8-46d2-8158-e029a0a5b9f1)



thread开到2时，异常如下：
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/e4b592ff-fc1c-402a-b29d-73c6a13f7964)
