### ISSUE TITLE
cookie里添加guestJs=有效期内unix时间戳

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#36]
用curl.exe测试，cookie设置Uid和Cid访问晴风村板块帖子（无登录要求）会先弹出“访客不能直接访问”网页（此处cookie设置了lastvisit)，后面浏览器重定向至帖子详情页，观察发现cookie设置了guestJs=lastvisit，guestJs是unix时间戳值且有时效限制

未使用这个python脚本测试

**Comment by ludoux** [comment]
脚本中相关代码使用 `allow_redirects=False` 参数访问nga页面，未出现跳转情况（可能是访问了`lite=js`所以不跳转？），脚本可以正常下载，就先不修复啦
