### ISSUE TITLE
tid=25009036不能保存

### ISSUE THREAD

**Issue by dfmjndm** [ludoux/ngapost2md#37]
Oops! 'NoneType' object has no attribute 'group'
Press to exit.

其他帖子可以正常使用

偶发情况，隔了一段时间后之后又可以，原因未知，推测可能是浏览速度有限制

**Comment by ludoux** [comment]
nga 可能会返回不完整的数据（应对非官方访问？）。稳定复现方式还有待观察……目前规避它好像就只能等待一段时间再重试
