### ISSUE TITLE
支持字体颜色，大小和表格？

### ISSUE THREAD

**Issue by proItheus** [ludoux/ngapost2md#38]
如题，这些都是能通过html标签实现的，可以直接用styles=...属性来控制样式。作者有空添加一下？

**Comment by ludoux** [comment]
主要是这几个样式，大多数帖子都不会涉及🤣所以都没加。先放着看之后有空再添加吧

**Comment by proItheus** [comment]
提了个pr #39

**Comment by ludoux** [comment]
谢谢～

**Comment by ludoux** [comment]
后面几天我会抽空更新一下readme和版本号
