### ISSUE TITLE
改了一下代码结构

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#42]
基本测试可用，只能把代码放剪贴板 
gzip解压：
H4sIAAAAAAAEAOV8Z3NbWXLod1XpP9ylSgYwIpEYJGJIyn5rr8v17J2pnZmyXSCKdQlckhiBAAZhJL3dcTGIScwSo0iJogLJkcQoSszUf3nGueHT/gV397kRAIPGM88fHkoCT+zTp9PpPgHXhKovqoRoKhZPtoeE7779Q9UtLLl65ZrQkculsyGfrz2e68i3eqOpTl8iH0vl7/mS7WI6lc0FO2NXr8Q706lMTshItuQPeSmby5oFKSuZvW+lc/FO6NSWSXXC+MmcdC+XiLcKemU0kcoCSmbj77OppJnpFHMd1nBiMpbq1AHFUwaAb3IZ6P9PX5ntOsRsBwxw9QrOrdH+YX2DhU8b8tTB1SsdkhiTMlmhUfjz1SsCfFzfZaVMldguJXOukOD6Y7vY8lVbWzwaFxO+W35/sNr109Ur0VTqTlyy9wIKfS1mszjwd/EY9qwL1tdW++tvuipLm/yeN/m3ejGXCv6YTtR3+OPpbNudf+OfH/w3k/U/VNfWxFvr6+MdJoSEmM39GM/GCbO//+qP3wr/8tXf/9Mf/t3RIA20KlP/E9LhRykDOLuqXZjJxWOQ8WMil5CwnBJQl0hFxUSneC8NZIDygFXSlkilEERVACFImQxMBviInV2c0NrUBpsYlec25dfHbLtHnt6iPuF4Mhe5eiUdjxHVfsJROyUjnZHSibiZy1uN8knRaCVcE/KIcZOgTK3Jg3swCrDPQMgP1fJil/Z2DsZFBnV2AgfNnjBuY5O6+UDdOGT9fWzjAFHleY6nstHFRqfZyAx79UCZ6L96pVOKxUXoHo4g5JEhbfmQHY4rTx6wzQN1e/mvxyP5TCJQ2RZPSIhjoDIdj1ZCUdAsClaK+Vg85fV6cbDc/bQEVHFBM1eli2pc8uCM68d4TEq5sIW8OY4Ee31c2B9WT04K+13yu2XWt6b1rsGw2vyDwtFH5cFHNjEm7/cpPx8ShtBRzOXEaAdRiSNLE2Lje4FKgXC0SoJUAt+E1NUrMalNQK1LSG7ktSfE5SgNmpRzu3KZ+1h6PeYSrgtUr1eLGbETh3PzPH6gNch0Jeh4zFNpL8Z+UE7dHRWJeA4rXN9nXTpc/U82GwDYhlHxfiNls/FU0q3X6qoXtilDBJpncxk3Io1S5cUvt0eo0k2FF/9gZW2lUO33eMpBIq1BQBW+DJgEb7ojfRvm0lgh3CDYOC/erV1CcQckvZByuwyj2dqa9YKGe6NJEwDMTjcvjfpfGwGsDydnI/9TaaDVqP+1RvVKSW62Udv+8X/9b5dOrkwUCrAeNdGLqiRGJbcLzAFQ1+URQCTUTwPy0St5bEib25HXX6BtVVdfys8m2MChNjXPAcXbhAp5cZQ9XGbza+zTfIUQTyL0kIU0FwxnK49VnZFy+UxS+IOYyEooXtSFuAlgvG3xZMztqmhp+a4iZLA8nQ06aiuh+k/26uqS6m+tasDYTfDRIHkEMARuAmjPVuvZklm4kAowxZh0T0imckJbKp+MuWyzke7Fc27oyUv4dx4WB93gAVZhHP1GnSeE84jwFkj/+84mwRs3qUl1xA4KF9TOeDaqt4PqkF7fnki1igmBrDEvMSy00Qeg6imDqtl86/dSNFcRqnB5bgRguiUtKivAiN+RYkg+jwMT0HMbdXCKsXgU8UcKeRMpMZZ1GxOvRG2A2kZiMgmXMvRB/jjEBrfASnHTXPi0LHdv2uUCaFIK0yRVGaCsb69w8hjN7cIz9mqUjDpnSlRK54QzuAk6lJUEWpbO5qQx7TYQkPyPQGgQc2PSXsiD2XHbxQWkzIX1aNNd1BgahZyazNepMNaEXbBMuSJoS/Ss0Tdi6EQmdTd7HjdJC77612+QVTcC/lJmYoOv/+4f/6HCYqW1XCM58D+O4vEF/QDCGJi+HULGF1C7NCBZMmmcp8m2clSBdWb9pXI0ztcWq7wtoaOQSYNlTeVdEY+DlG5sAOu1RwCjDMuAvlITYTNp0BPg/fgbee5UeXWorczg0vzkAV+pnSRHPKOdOd4vbMKJlEPW+BhuQRg6hmEp1vnU1plzUwm5pQjEiTOg3KRTqgio6X+0JZwCY0Di6OGs5PkNresJF2cnEHSKwm0JxARnQmg5W5CvZG8C4hATc1Jxu7wTkpjPdaQypeCcOWKzTgVOSYMIsPa5mpPNSZchP/YZcrcja5/h4hD3UsA5Ah5qXUPy8M9s4VQZGihlBbJPNLlnADuXe/rIIjAKvSlcrmEljHe2u85oTMQFhwcXTGOdhua0Tgdu3qIIh49MUuFz3UDYvAS6FZPN/rlmAMY/1qLrRacs3+n9Pt3OV9+zIRhuIsDQIxVvZ6zWfXYH/LSCvcy6ccxKwXAHGl35XFvVLTAF3g7pXizeDm6T2xMOhm5FgIHYNlxVFzpnLkBTkgFuXAy8PHzhRMZyrmoDI9rTF2SSkaXyzjIwnC2uFfaPwAjwWq6358+B/FavmE5LMBqidw6RStqb2H1GH/K5L+jAleAG+LQk8XzGwu/CIC4Rt9d3PeshRQBH+JIYFH2cjcFbayEUwUu9JnB/nw9ZqppxS/MRR7upxo+UQPaBCukegK4VEKUAX7QXc2x8Ul1eKxz2YzzxdJlbUhdy1R7+/A8bJH0KNBCaBMNOl9FrJ0lMg252t0E2HDJySvX10SCfEf10inck5KhpcPg3MuXwMvshvng2C/bKFwgKatcIe/GMPXyO5m99jvWsQUQHVAfygrHrFHMQuaGLdLgpzwzIi++gmTYwAB4TFEJkiFSv4g15PWra+izr25fnnrOtB3b0sndh7saGhxEZlbqNZknM6Oa9m4Gwy+26nkVxZvszbH3iegzTf8unZki5m8DweI7gO1yEBN84oDTY8TbyoSDKapfcfEW8ESjyoHgTFIdQCevdhpR4qA25UmU4n89mdHtpeFt6tyJhksCHPLe7S158oyy9djnbXNMdybZE4/UYYtrIA19wWCpNOfYUab1F0Sr4NCev4UdoyKZFCC0gegSeXo9VNF2PeZsbIB0CWjcJ17Ngx+G7wYftmmCQs02J29DFSgHxsHKmBlYaMyvGDShrKvL5OmXNQjcKLg8FjfNg1MHGt+bbz5o1CMtZFLEp6plEI2krcsv5913QOSEF5tsNi6rvesyH+gYLJHKE9hgE111XmTVQELNCm22KbfpQMCYYXXIu3B6PZQXQBvwoZVqiHVL0jmkEgHTm7kDRzl4k7OcWtsWFEWa5Zr93NiuNVb5OSCLGKbF4TvhCh/AF8KgthYzKdUi4PyvRSgNfGZi41wt2rC10qS1a0yTVX6OUzviqm7dqAjfrbvlrBDvP4sl0HlHKSNmskEtRrOQtCZ78RkDOJ/B7pBbuRFAMlUbLnwUcjW64oQJOCN9tNDdycLvEAksOGZ+JJNknQpyo4kB9GfGurxOhZewTBMC4JeTN3cu5PLTtYbDNbRv6d43I2dLA3ymMrqampj9KdwUdJt8G+F0YdLQRNTXS0NDQnNQZRttNl+IBBTcQ+BEzdZyMIX5HVgUylTZCeX4xS4rMnc6h73BbD+DbBxYy8faOnJBM3SVoXPgz+aQp9jZFKL+A8C1jHmASjlCA2wl2zdX72PeQy1bYAk+9xtxOtsuatfEGSon7NKmsFzfrvEAEkCrdPBhmwc5taNh5JxbPFDdxBMMCRj6luLbirgzfGL2vD3+3A9XR3Qqh4H37MLTjmE1IUtrt9wZsXCJ3MmDli2AaYbvhfzjROlMGrl7JdkL7FhE3jv5c0ZqIJ+9UhIQKf0VlRXsqFfs+1YrZAGQL+w8xGaTkuvzsDeaqIce695R3k5irwVz/HiZrMTkwUjjYxlwd5iYeY/IWJY8wWY/JyX4aAAdkj1YojaOxxzwdpPQ6pat5OkCZGp7RRw7QeDNzlL6J6U+9hC31WVilNMKV56cJbyyXt2cpjaCUZ2OURjjK6TNK11F6We7jXQjs6hTbHiRohNmn1cLxK8oiELnrEaVrKU29gghE7uWkQwjyg25KIx3kh4+V4R7KEi0eHxP+RK0ZImOAyDW3Y0yz3swSFYJ+gvJcOyaCVlN29rm6SQSrRhTV5S1iDVZpR5M632oQXfXhtjK7Sy1xGG32DesbolqizuMVg0BIOHXkI6URA3VjmQ0+0rqeUGNi1/goxAiYxTmqH56xiRGqDFb8ZMpYkGTMJlZ+QnDzI5v7RNlahzT5qy2S+olHejkOofW8LOy/+b9dJCX+W1xi2Ow7/o8KCdPBKVO8tHfH6oN9S3i4oHJqv1o1hKzWJnDEr+41U3gsuXfIFUIrnDxXFofhHyRMGYil2iWT8erAG3nwPRsfURY2TAmA2bKJXpN3gJM+SaI5e9nNHj0xWVnYH5V3jyD4MiUYS+bG1NUhNjZkiix4/xRHD6unj/XGtQGOIoQhysguuGKFAxLiWprGwY78dJOyNWY2SHkixnGPukEY19A0Nl4pi0uUvcWBsr0d3LlbNzCrqeXlMIyyOlo4PNS5VEPCu7LBxjfNb1PGdRUhAZcfvtCmF9krEs1anPl9KWsp0+JQ4WRa3f0AiJrmQpntY2sDpsVI5KN37ps2I52Km8oCPAta6rvWrVulGsx+n/o+pbwdNpVdzwdNDdELqk1F0AtqTD3QC2p1lTNlP53NkfAX9k/lIRrBj9gUDmkK/oBT8INmNmgqAs9Xm8rAeo6UxWNLbSjLm5NE901BMGaqC8Ttum5zXeFW169b4KBlgif7qy0bPDlt2eDJD/K753YzbLfCQbvqVFtqZRkuQmLp0LJpG32WQdsYkvu2LBYd7Csr46bSseMuw5gHzWzQUkLKV9tscJcyM2kzw48syel6FLTscNeaZYd7H+pyQHaYZ4OWRYU8JxhpJc8GTbXk+WprWeldM5cVeWZR5xKtLMbqU2dbfQiZ929MIYN00BQwyFSb5hsylqTJR8vqx/em7PJs0LTeSvdbeW7JNPXK0Lwyc2xqpzL1gQ3QklFDi9zisDw4bqo4YKy+GDZVHLKgjqYGA0fVrhGwPPoqU4uoKbur7Pi5aWqU0zE2+d5UX7V3xLQ2YIKVwxemteFZy9qofSS0tdyQLcE/nX61ZHy2eE9arvpJnmvraekiW17n52kCV4eIaEvvCwcEsS7IF0B9CahDXGDZVJe7KFtj6WqMq+qfvvrnfzaVU3d+uGb27Oi2hivm+BAbOGRjR5ZqWspW61AdrplcdbhaTvey8Ve6pfM713qunFzySTd1USbVNESZdFMX5UC1zY7W8LSlmJZbECihLV/ojJKgZZS5uHKj/H5NfjBuKinPBk0t1SWYVNSQYNJPpddaJPWZkWIaxo0007BsfKE0JYSUUx3dNDVTd2ZIK7UH8+qqpZXa7I6pkRabQSEtG9xOfJUH5+SZWfZwwbK8jwfZ9CuTv6BKbLDf5K8+JnFWHn6kHD21OMu5Q2wt7L9We3otzk70Ko8XbWx9afF07qXN4PYfmUzVpbuMzzsqjwyYbFVP3qmHb3XG/sQ3H/XLFzhPN0S5RkRBxyJROnnX3XxbqAHtMKAW75oHDm5XOBuCNhCoYnwjRnFjBKPXiNt24FHjOPGAdGtrljZUfDSIT4xeh6Aq2e6hyFSMVpqDh8WouedFqAVtqAUvgVrQRC34y1ALtjhwC5q4BcNiEHCzQibED1dtE0HIXIwhNtJRhOQvwjGds6MIUCotBMLwvwTLmA3J2CVwjJkoxn4ZhjEHhjETwVguHMs5GAwqZ9Gv/RLkazep1/7LiNfuIF67Sbv2cLrdQTnnfj5gYqlRUroLcbBDkaxm1ulcQ2vG14Tncrjr6CguU/o3idyX0P5v2nNfuirL1tmqDJ2+eoWfOaVpoyQc4ej9kE/lHMhdE+Tnx+x4HO+b0YEwv5TGtrZxlV7p5sdo8uxHbXYXfHQ2sXr7tmOrxBzFgBemMSJhvOhWU1NXdzMQrKmtDFb7a2pq/XWV1ZE/4eFR2Af1ESHcGvkaOIC70LiJHrkmJlPJ+y3Srfr6YFtrbW1NsFas97e1wb8af73UWlN/KxCtrwv7sHE4mkqkMo3tGfF+xF1TLb8+9oR9VBYR3EF/0F/lv1UVDAj+6lB10BMK+1ojRHf6Ul+81Rb32cCI/O5Q3V1SPw389XhEeTkNCfAplcXnsHbIu7OQVXt7/7OrhzpBZKLNbsiDkxAMFY66IBLCKOpZtzY/gYdaoy/g+6/HS9SWbXyE+MWndnWz/UEfxLRsfUXrPYEYCDpDnIVR35MH2tQ8jGsALxwsFY5e83qI+djettlEHlqXF3bw1GZsk73ohRDN6Afo4D2FxSGMEp926adre5sQJQEw9cMWYB/2ca6YTPJHADk2MSqEAxHOXSEcjLDFQTzr0e8l8qbseFqZWjPZilfR/PwT+TaVjkfDvlwZTuptInc7UvwfZ5nBl+qqYJ3gD4T8NzlfjNsoftqmRQVN43JkU3pXM8egOdJMOHhv3G7Ggbxf3G6OuCHnaaYhmiNY4nY3x/5c8xMVe0JQ02o10sG43bdDzUnPn/2VwZ88LjzUENuzjTD4N/pFtfnC/huKh4HJR2x/BihjKPQ9RDPlp2NqMZEghbLdWYnnpE5+beWezW7RuPp9LGoSDkbK15ppS89BtckuNNl3X6kdP8mEXqQ6bg45YD/p0A0m4JvNt7pdTeHv853piPsaaKDfI1zPuq9nPUJWxEOhrH7qdtYxkNs2ZKVgjFVpYQyWlxODQ6Dy36fyyZxusqOYdlfo0lRho9o96+TO6mXf3gQzowPhV48MmbZTJJsTMznrSNCArXODOgLOGbclTS6OcNFZVDSPFO30Ejx36XEW1jcgRuXOsHQcoM2ljgNbM5J4x36vJZqIp/lMwwQrBOPcuGWTlUwqcJaeULVdV9AMgzKA6Ff+lipjYUDGBVcdEAw2tlQ4WVS7+tC4GGamOqJu7oIyFfYX1defbLPS1SpgqhUSwuPk5Bm6ZcqaQ7+qI2e3uKyOmf0u1jNdNuytzztFdkLVT5JthUXIl7o9SJ5KhzqjIn+WPoNG84n4DSV26nbQodvOuRo2O3iezQYhovUeTw6KhVEwFowSqWzWxfIGiiWXSCxsvYQIXiB+TgsevJwFv2bMyHR2jAs9dL1QJ6CdPD+I5wkKCol4pmxQX0McRLva63Y8WGrHkeMmnbkEhC4y5TbGixa/iwx4OR8Xr8jekVL53EVebjgmJdDAuv7jP+w+a9hnL7fg5jMJJ8R7XLJMHoE8QRu7lGDOZWB8BvfOViAXgotcz4YREIUO1BUQowqkolnoOR+pRo7Tr4taI0Qwduwslp2tz2d9TDHE2WFkpE/ObS3ixYJcjvdiIt6evJBL1KqEJFRqEKWM6n4mgfggOokoU0Qk25zPo5erIRb/EYT6fkJqrEA7V0XAwHhWNOHVGKhtOgvwOZSCQCQhprPSucRyGkuzC3q3Hrs5NGrOoV7GePt0ASnxhps+EboWUnxllcNpiEk5MZ7INjUnBaEhm+/sFDP3m9jejvxwjo3jxTKl54ANHLHtaXbc1eAzWlDzdEYCit0QmkvJbgxdvOpS5EvXfBt82L05CYTXUSi6HlVOFgz6kCyYGVN5uXjn7BcXSn2x8yZ+wWzCgVCE4/55dAj8VnTQtcJOiYtMRlm9sYhW1hjQAkdLlbWf8E1awieKQq5DTN6hGwN/G81IgEcdb8Ej/CxdGUQ31qVM7RQOINiCf93y4EMIetnhE/V0gb18p8zvs3UIrSfZZh8b3VRPt9jeezY6iNfmpt5rfUPy4Ejh8LULhg0GS8EHCfzYsPx0jB0/Z4Nz2vyg/HRNO3rAJnbVDx/Y5Bo7nWDr89rP7+TFbbV3WX42q/WuF06mtbdzygmkJ+UX3erWC7YxzKYm1I19recx69/Uln6WFw7khVN2sq5OrKpTy/LJnDK1pU6+VF90Fw7HCifzbPyj+giGXlSHx7X1cWVtmE1M4xR3BgtHR2z1CRt9wXr6tEdLbHWR7U6pW+vsaEYd6ZW332jz/drApLL0Xh7cVXdPtaUV9mpc69mWZw4Kp5taz4HS/5CtLymrK8r8iby9pM2NqTMLbOtA3vigLexpR2NsfEc7ndfmP6q7h9ryqby5oPU+1U6faD0fCvsD2qNt3HP+MKOu9Mq7b+T1FXXsLVufkrdfsYlJtr8v7//MDvfkmRN5ZkAZWpDXHqqTC1oP0GFIO5mQ5x4XDqYKx6Ps8Jn2YpF1vWGHD9TuHuXtc22nm+28Vz4tyRt76s8HwCX53ara9Yn1vWd9W8qDlcKnZ2xvRV56r0zNKa+fspE+ttHNtp4o71bUwUfa3Ia8tKkcvpFf9ClvX+P2zOY0Podcf6m+3NUWR+WPPfLghDo8q27tKQsLuCXyqZv1D2lv+tXHT9W9TXl/H2RHe/pe2ViWl3bVR/PazigbHWMzR8rrbvXRjjz4ST6aZtuD2uuP6upLZWhJHTplW6+0uffgIio/97P+RTa+z0Yf4/HKxJBy/EbZ6FJPVrTlA/XTM/Xhina4or56wtYeKG9W5MEnbGdSnt9kfU/Yxlt194CNLrL+PXl+nO2vs9G3yvZ7eWmcbcwqzz7Jyz2sb61wssQOp9SBVW32gzq8pPW8U0+h1zO2+o7tD7JHI4WjAfn5qfZkmE33s0EQmHl19CXbe8s2B+TlSa13TJmC4GmhcLSjzj+Tp2fY3s/yHIjcnLz9XF56rR0eqcOT6ieA/JQ0o7bWvLZEusqj2ixebHS79B03lz0CTuY7DRc0fNN+X59fhIJq++6CbdkhBdTvZbn89/xo/KA1GZVAXdHzGxEi6GCwOPKmi3rQzWEmwnY32DaAAT8Qqj5zhNraywwRvGiI6lDtbzWESaa635hMN0P1vzWZ6kOBwK86hr7uuDM3XLeNuLxo8dabkLzaj7RsbxtCjj1r8xZhHLeKvnTcqosDogkp6aaOjlt8/JUNlYfjNgxtz2f0yhuBiGP2RRcF+TXi61n9dnus0nrJQU9d6O1hEaHOvNtnm1bRrUUTv3wigcPjM+kKfeiKMkMXDeh4iml86DK0/gMJbsd9WnoIBAyUxM7GbzN5nIqYBdZk06lk2W0v/EQ78sk7Ldn4/6HH/f5gDW04j07L75bVzT15u0de7ML7VV3H5ftbd7ONSeJt7Fb98jXM7JznWHT8JeZE7iFzNL24OdiiPztzW9g1WsmznoOZYGFU/aY3Qi+iqv5o9B/oD16EBTzLIanfnf0D+H1SDH2oWOpuEiUQohJ8wp7rgERIFyEivUWAElbSwLYfSLDSZV1T/Lgazh+6qXTg4pmW3+zUJ0YwYQaCXRUM7QnSo4IzZDOOd1mreZ6/rYomJDHjNq8Rp+PRC+JT9+2GxmZ8T9Uc8UCA5b4NOR/PXjZg57YAn+PbNwcIP9rHCPtDQR5eeX3FAdbnPAMEDiG0oH0R5v0v+9jvUo/7+GO+z3jLV/qUz/HOzfmU7qJnc+c+kSt72otv4TC+wb8XhTacQZWC22V/Q+d4P1c2xKEAB38c41LSBOF4tqOR2tulioo/Q65i+Yxobl/Tt37YcRtr0GI00kNsO+VTmbjRxUY2gm9ACp0FqkSs/mdE+v+VkOoLpf57Jb+66PLfUrlIeG2iQkJM+QvFGLhMQtyAD/rwim6XtvReezEZwkdclYJhkpF/9J6Bfk6CNhJakOQG7pUkYp6zRZ5+BeYzRJ7a/3dE/v8HufvVJIz/Rs/lJIzafoaEWYbSkjF1tV+XMS5elsk8U4DoAsaFO8T86oZzh5jf3fj1Noj5GNZWWCpTtEF8if1hF39Bqe8OExBwf77kO8PGo8lyIIUzCYReZBF9GouoQz5nEXGw7NejDY2gkwbTv2jr3EmcNnCbqxCWuXNehj7CJQiUE1udVxH1CUh07oX0cd/+uiEntjf5brup8V9ymb/kYh5P2F9VH/mCqORqaG6nNk26IcLfh1nYlcdeyw8fykNd+IsBg7Pq8pqysM/63kNLfPw8cyAPv2Pje/LUgTw4wbbw0kclO/iozb/CW7q5WKCCP01gE2P8Jwjk6S22PuvA03HRi/CjS108aVDrbjwGnjQEPf7rXwqtqUxMykAufU/IphLxmFFUZezghszzBJA9wwAU0aXBzcnQZEw/0GSMVjpAhUUXuurySl0eMa+CAVkgfRZ/WlOJ2Lns8d1u5Tz44ouzjytKwMZzYqLIdy8FHNcBfwbcfBJ/8CqaypSTKeeRGxccu1DTeVBMgt7kMoU4NLziV8oHByyfDkxXgjOxg8UaIGM0fd683Ym/ZDzNDohnEqAMMonSidG4ISEhteUumEnmzM70itPeu3R2nbnSidnvSNrL9fPyolIjnjN//cPRxXTQy1ZbzkzZauvOs73UuiMpXHO0dhx722uMg2sHZuZBqb3UcShYVKGvmo4hjaXCXmiZR3upqZT2QptKOfB1aoS9yiGOvML+XXwKBC5aSws6BC0t/I15S6cYT7aYT83pTe9/AWZdnKfpUwAA

**Comment by ludoux** [comment]
谢谢！不过我这几周事情有点多🤣后面我处理一下，多谢！

**Comment by ludoux** [comment]
真的抱歉🤣nga 现在时不时会阻断脚本访问，我最近又没怎么上论坛，这个项目就一直没有怎么处理
