### ISSUE TITLE
查看用户ip

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#44]
现在帖子详情页看不到ip只能在用户页看到，访问https://bbs.nga.cn/nuke.php?__lib=ucp&__act=get&uid=[UID]&lite=js然后读取 ipLoc的值即可得到 ip归属地

**Comment by oarinv** [comment]
该功能已添加#45

**Comment by ludoux** [comment]
感谢@oarinv .以及[新的 Go 重写的版本](https://github.com/ludoux/ngapost2md/tree/neo)目前还没有支持此功能，后期可能会增加。
