### ISSUE TITLE
pid=34945320的帖子保存时出现list index out of range

### ISSUE THREAD

**Issue by Ariescoco** [ludoux/ngapost2md#46]
![屏幕截图 2023-01-30 214746](https://user-images.githubusercontent.com/45306867/215498306-800a6f0b-08b4-47a5-bbf2-5378ab451ecf.png)

**Comment by CatSayInk** [comment]
你解决了吗

**Comment by crella6** [comment]
nga.py 94行 这里没有添加ip文本 

建议整体上移除ip功能因为nga限制了网页访问用户ip

**Comment by ludoux** [comment]
> nga.py 94行 这里没有添加ip文本
> 
> 建议整体上移除ip功能因为nga限制了网页访问用户ip

@crella6 谢谢，我后续处理一下。
话说推荐试一下新的那个 Go 语言重写的版本，我换了 API 接口，以及可以多线程下载，速度应该可以快一点

**Comment by oarinv** [comment]
> nga.py 94行 这里没有添加ip文本
> 
> 建议整体上移除ip功能因为nga限制了网页访问用户ip

移除IP功能#54，已经修复此问题。
