### ISSUE TITLE
Oops! 'NoneType' object has no attribute 'group' Press to exit.

### ISSUE THREAD

**Issue by CatSayInk** [ludoux/ngapost2md#47]
试了好几个帖子都是这种错误

**Comment by CatSayInk** [comment]
<img width="429" alt="图片" src="https://user-images.githubusercontent.com/26319155/228404593-3abe057b-931b-490a-a247-1e6c00df14d0.png">
也有Oops! list index out of range这个错误

**Comment by ludoux** [comment]
这个问题最近一直没有跟进🤣sorry. 主要是后面想换成golang来重新写，就没有修python 版本bug的想法。目前代码 下太长的帖子就容易翻车
________________________________

**Comment by CatSayInk** [comment]
好吧 期待你的go版本

**Comment by crella6** [comment]
关闭获取ip功能解决这个问题

**Comment by oarinv** [comment]
移除IP功能#54，已经修复此问题。
