### ISSUE TITLE
NEO 版本测试

### ISSUE THREAD

**Issue by ludoux** [ludoux/ngapost2md#48]
### ngapost2md_NEO_PRE_0.0.1_20230515

@CatSayInk @proItheus @oarinv @crella6 

目前新版本基本实现了大多数旧版功能，具体参见 neo 分支的 [README](https://github.com/ludoux/ngapost2md/blob/neo/README.md)。

假如各位方便或者正在使用旧版的话，欢迎用这个新版的测试一下，捉捉 bug。多谢多谢 :) 😄 （特别是reply等格式在md文件里的排版等bug）

使用说明也请见 neo 分支的 [README](https://github.com/ludoux/ngapost2md/blob/neo/README.md)。简单来说就是需要更改 `cookies.json` 里面的两个 `MODIFY_ME` 文本 和 `config.ini` 里的 UA  `MODIFY_ME` 文本。

Windows 调用方式如下
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/82ed6c1b-8f36-43eb-b79b-cf933041e4e9)

文件在下文链接的压缩包里，里面有AMD64架构的Linux版和Windows版，任一测试即可。

下载：[ngapost2md_NEO_PRE_0.0.1_20230515.zip](https://github.com/ludoux/ngapost2md/files/11487086/ngapost2md_NEO_PRE_0.0.1_20230515.zip)   
(20230516: 应用了PR #51 ，已修复 `config.ini` 字段错误)

**Comment by oarinv** [comment]
User-Agent怎么设置

**Comment by ludoux** [comment]
我这边目前的测试来看，使用普通桌面浏览器的UA即可。还没有遇到一定要nga客户端UA才能下载的帖子。
________________________________

**Comment by ludoux** [comment]
> User-Agent怎么设置

@oarinv 
我这边目前的测试来看，使用普通桌面浏览器的UA即可。还没有遇到一定要nga客户端UA才能下载的帖子。

**Comment by oarinv** [comment]
```
2023/05/16 15:56:15 bad response, raw dump:

panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/ludoux/ngapost2md/nga.(*Tiezi).page(0xc000122580, 0xc000012018?)
	/home/luu/code/go/ngapost2md/nga/nga.go:169 +0x9a7
github.com/ludoux/ngapost2md/nga.(*Tiezi).InitFromWeb(0xc000122580, 0xc00006f870?, 0x972ce0?)
	/home/luu/code/go/ngapost2md/nga/nga.go:193 +0x10a
main.main()
	/home/luu/code/go/ngapost2md/main.go:41 +0x505
```
无法运行

**Comment by ludoux** [comment]
> ```
> 2023/05/16 15:56:15 bad response, raw dump:
> 
> panic: runtime error: makeslice: len out of range
> 
> goroutine 1 [running]:
> github.com/ludoux/ngapost2md/nga.(*Tiezi).page(0xc000122580, 0xc000012018?)
> 	/home/luu/code/go/ngapost2md/nga/nga.go:169 +0x9a7
> github.com/ludoux/ngapost2md/nga.(*Tiezi).InitFromWeb(0xc000122580, 0xc00006f870?, 0x972ce0?)
> 	/home/luu/code/go/ngapost2md/nga/nga.go:193 +0x10a
> main.main()
> 	/home/luu/code/go/ngapost2md/main.go:41 +0x505
> ```
> 
> 无法运行

@oarinv 谢谢反馈。方便提供一下帖子id么，我这边测试一下。

以及为了避免是配置错误引起的，下面是我的一个配置信息，供参考
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/ae11f5e2-7048-442a-a452-2121245866ad)

**Comment by oarinv** [comment]
33450877
ua 是 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

**Comment by ludoux** [comment]
> 33450877 ua 是 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36



你好，@oarinv  我用那个UA测试的是可以的，
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/614c087c-7b7e-4030-8771-19e44bfd0ac1)

报bad response错误应该是直接网络请求都没有请求成功，可能是应用发送网络请求失败了？我这边测试断网情况下就会报这个错误（见下图），可能是网络环境有问题或者应用没有办法请求网络（比如代理配置有误等等）。

假如你那边调整网络环境后这个问题依旧，我后面可以做一个最小的网络测试demo，你方便的时候可以帮忙测试一下。多谢多谢

![图片](https://github.com/ludoux/ngapost2md/assets/13460812/27557f3a-0d74-4c6a-83d6-1c176e4b30c0)



报错代码位置如下：
https://github.com/ludoux/ngapost2md/blob/919eaf73df0d99b3a7624c10c7a5d5d1f673e198/nga/client.go#LL47C16-L47C22

**Comment by oarinv** [comment]
可能代理问题吧

**Comment by oarinv** [comment]
平台：windows11 22h2
命令：.\windows_x64.exe  21731571

输出：
```
ngapost2md (c) ludoux [ GitHub: https://github.com/ludoux/ngapost2md/tree/neo ]
Version: PRE_0.0.1_20230515

Start page 1
2023/05/16 17:47:57 bad response, raw dump:

panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/ludoux/ngapost2md/nga.(*Tiezi).page(0xc0000ae580, 0xc00000a018?)
        /home/luu/code/go/ngapost2md/nga/nga.go:169 +0x9a7
github.com/ludoux/ngapost2md/nga.(*Tiezi).InitFromWeb(0xc0000ae580, 0xc00005b7c0?, 0xd1ce80?)
        /home/luu/code/go/ngapost2md/nga/nga.go:193 +0x10a
main.main()
        /home/luu/code/go/ngapost2md/main.go:41 +0x505
```
重置网络、关闭代理和切换热点后，问题依旧

**Comment by ludoux** [comment]
> 已经修复问题，拼写错误#51

多谢，已更新主楼的压缩包内的配置文件内容为此PR后的。 （改配置忘记改 assets 文件夹里的了……）
