### ISSUE TITLE
Posts of the main zone cannot be processed.

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#5]
windows cmd>python nga_20200623.py
tid:22959845
22959845
localmaxpage1
localmaxfloor-1
trypage1
Traceback (most recent call last):
  File "nga_20200623.py", line 185, in <module>
    main()
  File "nga_20200623.py", line 144, in main
    holder()
  File "nga_20200623.py", line 163, in holder
    while single(cpage) != False:
  File "nga_20200623.py", line 41, in single
    usertext = re.search(r',"__U":(.+?),"__R":', content, flags=re.S).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I am a Chinese user.貌似网事杂谈区主区的很多帖子都抓取不了，提示错误如上；但是分区的帖子可以抓取。建议多从主区找帖子来试试。

**Comment by ludoux** [comment]
你好。
由于我当下用不了电脑，所以没有办法复现。但是有两个可能的排错方向：
1. 请问一下 cookie 是否配置正确，马桶区基本都要登录才能看，而分区基本不用。假如 cookie 配置错误的话可能会无法以登录状态抓取数据，而脚本目前没有针对此情况有处理，会直接抛出异常。
2. 请问帖子状态是正常状态（而不是被锁定）的么，当帖子被锁定后，也会出现这种直接异常。

（前几天我还从水区存了帖子，我个人感觉可能是 cookie 的问题😅，我过几天有可能会针对没有登录、帖子被锁定写一下错误输出）
________________________________

**Comment by crella6** [comment]
啊不好意思，确实是我忘记填cookie信息了，我也很纳闷一直看不懂正则表达式有什么错。
