### ISSUE TITLE
支持原有的 `smile.zip` 本地表情方案

### ISSUE THREAD

**Issue by ludoux** [ludoux/ngapost2md#58]

**Comment by ludoux** [comment]
需要下载 本地表情资源 （后续提供）
配置文件：
`use_local_smile_pic` 是否使用本地表情图片资源而不是引用在线资源。默认值False（不启用）
`local_smile_pic_path` 本地表情图片资源路径。支持绝对路径与相对路径。尾部需要以 / 结尾。

**Comment by XDcedar** [comment]
请问是否有 `smile.zip` 文件？在仓库的什么位置提供了，我没找到..网上找的表情包命名对应不上..

**Comment by ludoux** [comment]
[smile-resized.zip](https://github.com/ludoux/ngapost2md/files/12853444/smile-resized.zip)


> 请问是否有 `smile.zip` 文件？在仓库的什么位置提供了，我没找到..网上找的表情包命名对应不上..

@XDcedar 这个后面一直忘记上传……这个压缩包的表情忘记是怎么下载下来的了，好像比论坛的那个稍微高清一点点。解压后修改一下文件夹名字就可以了

**Comment by XDcedar** [comment]
非常感谢！
