### ISSUE TITLE
v1.4.0，无法对已爬取的帖子进行更新

### ISSUE THREAD

**Issue by PhiFever** [ludoux/ngapost2md#66]
查看文件夹内部`process.ini`的内容正常写入了max_floor和max_page，但重新运行此tid时发现无法像v1.2.0那样增量更新文件，仍然从第一页开始爬取处理。且运行程序后查看markdown文件发现文件内容没有增加，`process.ini`中的内容没有改变。
`config.ini`中的相关配置为
```
thread=1
page_download_limit=100
get_ip_location=False
enhance_ori_reply=True
use_local_smile_pic=False
local_smile_pic_path=../smile/
use_title_as_folder_name=True
use_title_as_md_file_name=True
```

**Comment by ludoux** [comment]
多谢，待排查。~可以先用1.2.0~ **可以先用1.3.0**，目前不会强制更新

**Comment by PhiFever** [comment]
请问1.2.0是目前的稳定版本吗？

**Comment by ludoux** [comment]
对不起说错了，是1.3.0，即上一个版本。

**Comment by PhiFever** [comment]
> 对不起说错了，是1.3.0，即上一个版本。

好的，非常感谢

**Comment by ludoux** [comment]
11103ff2a37067f6b6d2f744e60d7609215e419e 尝试修复了一下。当时编码的时候测试不到位，十分抱歉。

附件里是临时编译的 windows amd64 版本，只需要替换二进制文件即可，不需要修改配置文件（仍使用 1.4.0 配置文件）

@Gungnir762 @oarinv 请两位方便时，使用此临时版本测试一下此问题是否被修复，多谢。

假如此bug不再复现，后续会推  1.4.1 ，并在 release 页面删除 1.4.0 版本发布页面。

[ngapost2md-fix66_v1.zip](https://github.com/ludoux/ngapost2md/files/12231169/ngapost2md-fix66_v1.zip)

**Comment by oarinv** [comment]
沒問題了

**Comment by ludoux** [comment]
> 沒問題了

谢谢。已推送 1.4.1 于 release 页面，同理未开启强制更新。

**Comment by PhiFever** [comment]
更新功能没问题了。另外报告一个不知道是bug还是feature的东西，每次运行程序后`config.ini`中的ua字段会被截断并且末尾缺少右引号，情况如下图：
![image](https://github.com/ludoux/ngapost2md/assets/83220033/18c21263-4a6d-488e-9fb6-35f9bc00eca1)

**Comment by ludoux** [comment]
> 更新功能没问题了。另外报告一个不知道是bug还是feature的东西，每次运行程序后`config.ini`中的ua字段会被截断并且末尾缺少右引号，情况如下图： ![image](https://user-images.githubusercontent.com/83220033/257677617-18c21263-4a6d-488e-9fb6-35f9bc00eca1.png)

这个请使用反引号把ua值包裹起来，如下图所示。

```
; 浏览器User-Agent，通常来说填写你常用浏览器的UA即可。修改时请将两个分号和内部英文、空格等均替换删除修改。
ua=`<;MODIFY_ME;>`
```

----

**Edit:** 1.4.2 后优化了描述，为：
```
; 浏览器User-Agent，通常来说填写你常用浏览器的UA即可。修改时请将 两个尖括号及内部所有文本 均替换删除修改，且确保值是被反引号所包裹。
ua=`<;MODIFY_ME;>`
```

**Comment by PhiFever** [comment]
明白了，我的问题，非常感谢！（我看vscode显示的颜色不对下意识的改用双引号把UA包起来了）
![image](https://github.com/ludoux/ngapost2md/assets/83220033/605de30a-dcc6-4dd8-a61d-42be09af00d2)
