### ISSUE TITLE
能否在强制更新时产生一些独立于CLI的提醒信息，例如产生一些文件？

### ISSUE THREAD

**Issue by RichardGuyNotFavMHY** [ludoux/ngapost2md#71]
感谢您的工作。请问在未来的版本里，触发强制更新后本地软件能否提供一些除了CLI之外的信息，例如生成一个YouNeedxxx的文件？
我的应用场景使用了Windows power shell作为驱动，其中我采用了Jobs方法来运行您的程序，但是Jobs方法不一定总能抓取到程序的输出，在无人值守的情况下突然强制更新有可能会导致服务中断。如果有除了CLI外的检测方法(例如基于文件的程序运行状态简报)，则可以更方便的处理异常情况。

**Comment by ludoux** [comment]
计划会在下一版或者后续版本提供相关功能，以及支持强制禁用 强制更新

**Comment by ludoux** [comment]
https://github.com/ludoux/ngapost2md/releases/tag/1.5.0

新版已释出，目前还未开启强制更新，欢迎使用。

新引入的参数 `--dump-update-info`，支持在当有强制更新时输出 `NEED_UPDATE` 文件。用法如 `ngapost2md.exe tid --dump-update-info`
