### ISSUE TITLE
NEO_1.4.2存在无意中覆盖用户配置文件到默认配置的情况

### ISSUE THREAD

**Issue by RichardGuyNotFavMHY** [ludoux/ngapost2md#75]
现象：NEO_1.4.2存在无意中覆盖用户配置文件到默认配置的情况。
推断：在config.ini被外部编辑、占用或者ngapost2md.exe存在多个实例同时调用config.ini时，NEO_1.4.2有可能会直接将用户的有效配置文件覆写为空白的配置文件。
复现方法：模拟config.ini暂时不可用的场景(例如外部编辑或同时调用)，随后使用一个脚本来观察文件是否有更改。
本地复现结果：
![图片](https://github.com/ludoux/ngapost2md/assets/140698973/c0287d4d-8f61-4c7f-ba7c-6ed7fbea0639)
使用的脚本：
[filetest.zip](https://github.com/ludoux/ngapost2md/files/12308357/filetest.zip)

**Comment by ludoux** [comment]
这个计划下一个版本优化一下配置文件读取，#72 ，在版本号相异的情况下才更新保存配置文件，希望可以解决此文件

**Comment by ludoux** [comment]
[app-amd64.zip](https://github.com/ludoux/ngapost2md/files/12311414/app-amd64.zip)
你好，方便的时候可以用这个测试一下么？由 9b901556b8d5e23b2b2ab8ca1b90e12510ddaa81 编译而来，不知道能不能解决此问题。谢谢

**Comment by RichardGuyNotFavMHY** [comment]
可行，但是需要等待一会。服务器down了联系不上机房。预计10个小时后有答复。
测试已经开始。

**Comment by RichardGuyNotFavMHY** [comment]
目前不会替换文件了，导出默认配置文件的功能也正常。
