### ISSUE TITLE
gitee的检查更新文件失效

### ISSUE THREAD

**Issue by PhiFever** [ludoux/ngapost2md#80]
![image](https://github.com/ludoux/ngapost2md/assets/83220033/68270204-4e5d-4a2d-8f6b-7741b250c963)
2023.8.26 11:00左右发现一直报错“需要检查更新”，增加参数`--force-no-check-update`程序可以正常运行，查看源代码后发现是gitee的链接失效造成的。
```
func checkUpdate(dump bool) {
	resp, _ := req.C().R().Get("https://gitee.com/ludoux/check-update/raw/master/ngapost2md/version_neo.txt")
	//版本更新配置文件改为 DO_NOT_CHECK ，软件则不会强制使用最新版本
	if resp.String() != nga.VERSION && resp.String() != "DO_NOT_CHECK" {
		if dump {
			f, _ := os.OpenFile("NEED_UPDATE", os.O_CREATE|os.O_WRONLY, 0666)
			_, _ = f.Write(resp.Bytes())
			defer f.Close()
		}
		log.Printf("目前版本: %s 最新版本: %s", nga.VERSION, resp.String())
		log.Fatalln("请去 GitHub Releases 页面下载最新版本。软件即将退出……")
	}
}
```
我认为检查更新函数的条件是不是改成类似于
```
if resp.String() != nga.VERSION && resp.String() == "CHECK" {
```
会更好一点？毕竟gitee的奇妙审核机制抽风也不是一天两天了……

**Comment by ludoux** [comment]
fixed in #79 ，直接推了新版1.5.1禁用更新了。gitee 被限制外链了草。
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/007970e3-61ae-47de-9a12-921451e755be)


Windows 下的话直接双击 .bat 就可以原地更新，注意GitHub要能顺畅访问
