### ISSUE TITLE
Version: NEO_1.5.1在保存 38195774 时会卡住

### ISSUE THREAD

**Issue by RichardGuyNotFavMHY** [ludoux/ngapost2md#83]
运行平台：Win10 PowerShell环境
保存的帖子： 38195774
现象：程序报错并卡住 无法自动恢复
控制台的log以附件的形式提供
[CLIOutPut.txt](https://github.com/ludoux/ngapost2md/files/13200022/CLIOutPut.txt)

**Comment by ludoux** [comment]
这个分区或者这个帖子之后会被冲水或者有概率被锁隐么，因为我最近比较忙可能要过几周才能排查😂不知道到时候帖子还能不能看
________________________________
From: RichardGuyNotFavMHY ***@***.***>
Sent: Monday, October 30, 2023 9:58:43 AM
To: ludoux/ngapost2md ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ludoux/ngapost2md] Version: NEO_1.5.1在保存 38195774 时会卡住 (Issue #83)


运行平台：Win10 PowerShell环境
保存的帖子： 38195774
现象：程序报错并卡住 无法自动恢复
控制台的log以附件的形式提供
CLIOutPut.txt<https://github.com/ludoux/ngapost2md/files/13200022/CLIOutPut.txt>

**Comment by RichardGuyNotFavMHY** [comment]
有概率，现在后排吵架挺厉害的😂。不过log是有了的，需要其他支持可以先说，可以直接把整个网页的源码保存下来供分析之类的。

**Comment by ludoux** [comment]
那我这两天看一下，希望不会被锁的太早
________________________________

**Comment by RichardGuyNotFavMHY** [comment]
实际上这个bug应该出现了很多次了。
(大概表现为在拉取帖子的时候突然卡住，无响应。并不是今天才有的事情，很难复现。

**Comment by ludoux** [comment]
```
"[quote][pid=723948070,38195774,4]Reply[/pid] <b>Post by [uid=64469352]大洋海神草[/uid] (2023-10-29 21:09):</b>\n\n![偷笑](https://img4.nga.178.com/ngabbs/post/smile/ac4.png)希望你在宵u凌u面前也敢说这话[/quote][quote][pid=723948070,38195774,4]Reply[/pid] <b>Post by [uid=64469352]大洋海神草[/uid] (2023-10-29 21:09):</b>\n\n![偷笑](https://img4.nga.178.com/ngabbs/post/smile/ac4.png)希望你在宵u凌u面前也敢说这话[/quote]![img](./74_3283bd31.png)闹麻了，宵宫被打断腿跟万叶有什么关系。\n怕你不知道我告你一声，宵宫在2.4之前最主流的队伍是宵宫武装和宵行钟班，云堇来之后变成宵行钟云、宵宫武装和宵行钟班平分天下，夜兰来之后宵夜钟云短暂成为最主流配队。\n不管什么时候万叶都没在宵宫队伍里面当过主流，之前我记得宵宫厨子算宵夜万班还被dissExcel战神来着~~我记得我也嘴过这个队伍来着![img](./74_3283bd31.png)~~\n绫人被万叶打断腿指的是给52增伤的钵钵鸡还有一个纯色c被万叶2命虚空占模吗![img](./74_3283bd31.png)\n![img](./74_3283bd31.png)我说得再露骨一些，0命完美适配主c的辅助对于主c玩家来说是好辅助摩多摩多；辅助命座比主c自己命座提升高的辅助~~或者说普罗大众这么认为~~对于主c玩家来说当然是不能接受的了。\n公子例子相对特殊，我不聊性别相关的东西，只聊强度相关。公子是一个1.1的角色，且在1.3才有双火论开始推广，1.4到1.5才是双火大肆发展，1.6就出了完美适配公双火的辅助；再加上1.3-1.5期间公双火是搭配温迪也好砂糖也好还是q老师最爱的甘雨也好都是被公子玩家认可的，说白了不管配什么都比那个cjb武装好一百倍![img](./74_3283bd31.png)万叶是公子双火队的最佳第四人，但公子双火不要万叶之前是真的有人长时间玩过且证明能玩的(最起码我1.3入坑就是靠公双火+砂/温一直满星到万叶出之前，而且当时NGA在q老师反向卖货之后一直有公双火热)\n赛妮两个人被草神占模严重，妮露还好说，但赛诺是既被占了模又没做到完美适配，再加上3.4海森横空出世直接破了大防；海森恩怨太多了就不赘述了![img](./74_3283bd31.png)\n当然还有更重要的一点是社区风评，万2除了万达就没有主流队需要的，而草2则是几乎所有草系队的命座最强优先级，这当然不可同日而语。"

```

quote了相同内容，第一次匹配直接把两次都给替换了，所以第二次匹配的时候就下标溢出了。做了一个判断

**Comment by ludoux** [comment]
我这边测试新版就不会出现卡死了。假如后面还有类似问题麻烦继续反馈，谢谢
