### ISSUE TITLE
请问一下python版里面User-agent部分是填写什么？

### ISSUE THREAD

**Issue by Pt2Mu** [ludoux/ngapost2md#85]
rt
User-agent这部分是填写登录的手机号还是？

**Comment by ludoux** [comment]
填写任意浏览器的user-agent（或者ngaapp的user-agent）。以及python 版本目前是停止维护的状态
________________________________
From: Pt2Mu ***@***.***>
Sent: Tuesday, December 5, 2023 5:13:04 PM
To: ludoux/ngapost2md ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ludoux/ngapost2md] 请问一下python版里面User-agent部分是填写什么？ (Issue #85)


rt
User-agent这部分是填写登录的手机号还是？

―
