### ISSUE TITLE
获取tid=23259348异常

### ISSUE THREAD

**Issue by crella6** [ludoux/ngapost2md#9]
获取tid=23259348异常，在down:./23259348/9184841e.jpg Floor[1404/1432] 之后报错 Oops! '[/quote'

我检查一下，应该是第1410楼，
```
[quote][pid=451719713,23259348,71]Reply[/pid] [b]Post by [uid=61815177]青青园中韭[/uid] (2020-09-11 15:54):[/b]<br/><br/>大师还是很厉害的，隆基我来说两句吧（省略……）机构票贸然跑进去容易被一顿胖揍。大师挺住！[s:ac:[/quote]<br/><br/>本周发言背景准备：<br/>周末陪孩子参加教师节活动，很有意义的一周（省略……）以维系在这波新人中自己的形象。
```
由于用正则匹配表情包bbcode在正则匹配引用bbcode之前，而这里 **[s:ac:[/quote]** 是nga自己的格式错乱问题，所以正则匹配表情包的时候在smile_ac词典里找不到键名[/quote，从而抛出KeyError异常。

**Comment by ludoux** [comment]
谢谢！我争取尽快把三个还在鸽子的 issues 一起修掉😅

**Comment by ludoux** [comment]
这个在 format 里面加了错误捕获，出错的话（应该）直接原样吐回去，先这样子了😅谢谢！
