### ISSUE TITLE
nga 返回代码不为0: 46

### ISSUE THREAD

**Issue by ChengLanEric** [ludoux/ngapost2md#94]
代码小白，认真阅读并且按照其他issue所提供的方法，查找复制我浏览器（Chrome）的UA，配置好CID和UID（f12-应用选项卡里找到的），首先使用管理员权限CMD打开软件，输入.\ngapost2md.exe 39773215，最后返回了一个错误代码叫：nga 返回代码不为0: 46。翻阅相关资料并未找到此行错误代码所代表的消息，更换其他人的账号发现并没有用，重新下载也无法改善。请问能否补充完善一下各种问题的解决方法？
![微信截图_20240406103551](https://github.com/ludoux/ngapost2md/assets/129480047/6cb2b7d9-0207-4bc7-9dcb-4b3e6c0d9b45)

**Comment by ludoux** [comment]
请试一下打开普通权限的CMD，然后依次
```
cd /d E:\ngapost2md-NEO_1.5.2-windows-amd64
ngapost2md.exe 39773215
```
下面是我根据我的文件夹地址所采取的代码，你应该按上面的就行
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/55309f70-2d61-476f-8528-66328fbae0e8)

假如仍然不行的话，然后请如下图所示截图并打码一下config.ini配置文件发上来，谢谢。
![图片](https://github.com/ludoux/ngapost2md/assets/13460812/37f3d2ea-6db9-4be9-9274-0d5958df84dc)

因为我也不知道nga返回 46代码是啥😂代码里忘记读取返回的错误信息了

**Comment by ChengLanEric** [comment]
非常感谢，已经解决。

**Comment by skydvky** [comment]
我也是个小白，遇到了LZ一样的问题，说一下我的错误原因。
ngaPassportUid和ngaPassportCid配置错误，因为第一次没登陆使用的默认ngaPassportUid，然后发现Cid要登录后才有，于是又登录了NGA账号，登陆后Uid发生了变化，要重新配置。

**Comment by oarinv** [comment]
登录之后，刷新浏览器页面，在F12中cookie里面复制 cid 和uid

**Comment by AlarmP4** [comment]
<img width="1424" height="975" alt="Image" src="https://github.com/user-attachments/assets/6da717a7-2158-404e-a5cd-7a78cc9e759a" />
<img width="850" height="133" alt="Image" src="https://github.com/user-attachments/assets/f2c3d71e-adb8-46cf-aecd-1d73bbc53f55" />
同小白，遇到了和楼主一样的问题。已经重新登陆并更新config的Uid和Cid配置，仍旧提示nga 返回代码不为0: 46 访客不能直接访问

**Comment by ludoux** [comment]
> <img alt="Image" width="1424" height="975" src="https://private-user-images.githubusercontent.com/254085163/534200061-6da717a7-2158-404e-a5cd-7a78cc9e759a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMDYxLTZkYTcxN2E3LTIxNTgtNDA0ZS1hNWNkLTdhNzhjYzllNzU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWM2OGI3YzQ0N2E1M2VhMzI4ODljM2Q0NTUwZDY4MTQ4Zjg2MGFkYWRkNzljZWM4NGM5ZTdmZDBmOGY2MzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nUd_EdZBFCf-TiOyxVXFkNrDy_MDLobW4YXTsgLSf5U"> <img alt="Image" width="850" height="133" src="https://private-user-images.githubusercontent.com/254085163/534200246-f2c3d71e-adb8-46cf-aecd-1d73bbc53f55.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMjQ2LWYyYzNkNzFlLWFkYjgtNDZjZi1hZWNkLTFkNzNiYmM1M2Y1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTEwNGZiNGY4MTkwMDYzMmY1MGZmOTM3OTRkMzExOGM2NWIyYWQ5Zjc5OWUyNDRjNDFjMTM3MmYyMWI4MWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6QfFrzL7ImIq723yeZF8P9kZYm5U3Lb7WhZ49crryVs"> 同小白，遇到了和楼主一样的问题。已经重新登陆并更新config的Uid和Cid配置，仍旧提示nga 返回代码不为0: 46 访客不能直接访问

@AlarmP4 请提供一下tid号，我这边测试一下

**Comment by AlarmP4** [comment]
> > <img alt="Image" width="1424" height="975" src="https://private-user-images.githubusercontent.com/254085163/534200061-6da717a7-2158-404e-a5cd-7a78cc9e759a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMDYxLTZkYTcxN2E3LTIxNTgtNDA0ZS1hNWNkLTdhNzhjYzllNzU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWM2OGI3YzQ0N2E1M2VhMzI4ODljM2Q0NTUwZDY4MTQ4Zjg2MGFkYWRkNzljZWM4NGM5ZTdmZDBmOGY2MzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nUd_EdZBFCf-TiOyxVXFkNrDy_MDLobW4YXTsgLSf5U"> <img alt="Image" width="850" height="133" src="https://private-user-images.githubusercontent.com/254085163/534200246-f2c3d71e-adb8-46cf-aecd-1d73bbc53f55.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMjQ2LWYyYzNkNzFlLWFkYjgtNDZjZi1hZWNkLTFkNzNiYmM1M2Y1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTEwNGZiNGY4MTkwMDYzMmY1MGZmOTM3OTRkMzExOGM2NWIyYWQ5Zjc5OWUyNDRjNDFjMTM3MmYyMWI4MWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6QfFrzL7ImIq723yeZF8P9kZYm5U3Lb7WhZ49crryVs"> 同小白，遇到了和楼主一样的问题。已经重新登陆并更新config的Uid和Cid配置，仍旧提示nga 返回代码不为0: 46 访客不能直接访问
> 
> [@AlarmP4](https://github.com/AlarmP4) 请提供一下tid号，我这边测试一下

🙏🏻tid=27917319

**Comment by ludoux** [comment]
> > > <img alt="Image" width="1424" height="975" src="https://private-user-images.githubusercontent.com/254085163/534200061-6da717a7-2158-404e-a5cd-7a78cc9e759a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMDYxLTZkYTcxN2E3LTIxNTgtNDA0ZS1hNWNkLTdhNzhjYzllNzU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWM2OGI3YzQ0N2E1M2VhMzI4ODljM2Q0NTUwZDY4MTQ4Zjg2MGFkYWRkNzljZWM4NGM5ZTdmZDBmOGY2MzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nUd_EdZBFCf-TiOyxVXFkNrDy_MDLobW4YXTsgLSf5U"> <img alt="Image" width="850" height="133" src="https://private-user-images.githubusercontent.com/254085163/534200246-f2c3d71e-adb8-46cf-aecd-1d73bbc53f55.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMjQ2LWYyYzNkNzFlLWFkYjgtNDZjZi1hZWNkLTFkNzNiYmM1M2Y1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTEwNGZiNGY4MTkwMDYzMmY1MGZmOTM3OTRkMzExOGM2NWIyYWQ5Zjc5OWUyNDRjNDFjMTM3MmYyMWI4MWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6QfFrzL7ImIq723yeZF8P9kZYm5U3Lb7WhZ49crryVs"> 同小白，遇到了和楼主一样的问题。已经重新登陆并更新config的Uid和Cid配置，仍旧提示nga 返回代码不为0: 46 访客不能直接访问
> > 
> > 
> > [@AlarmP4](https://github.com/AlarmP4) 请提供一下tid号，我这边测试一下
> 
> 🙏🏻tid=27917319

@AlarmP4 你好，我这边测了一下，假如uid和cid正确的话，应该确实是可以下载这个帖子了。而且我看你的操作和最新程序的一些限制，程序应该是读取到了你提供的uid和cid。

后面可能要麻烦你重新获取并设置一下新的uid和cid。用浏览器的无痕窗口打开并登录nga，在登录完毕后再获取相关的uid和cid值并设置，尝试一下

**Comment by AlarmP4** [comment]
> > > > <img alt="Image" width="1424" height="975" src="https://private-user-images.githubusercontent.com/254085163/534200061-6da717a7-2158-404e-a5cd-7a78cc9e759a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMDYxLTZkYTcxN2E3LTIxNTgtNDA0ZS1hNWNkLTdhNzhjYzllNzU5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWM2OGI3YzQ0N2E1M2VhMzI4ODljM2Q0NTUwZDY4MTQ4Zjg2MGFkYWRkNzljZWM4NGM5ZTdmZDBmOGY2MzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nUd_EdZBFCf-TiOyxVXFkNrDy_MDLobW4YXTsgLSf5U"> <img alt="Image" width="850" height="133" src="https://private-user-images.githubusercontent.com/254085163/534200246-f2c3d71e-adb8-46cf-aecd-1d73bbc53f55.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgxMDAzODYsIm5iZiI6MTc2ODEwMDA4NiwicGF0aCI6Ii8yNTQwODUxNjMvNTM0MjAwMjQ2LWYyYzNkNzFlLWFkYjgtNDZjZi1hZWNkLTFkNzNiYmM1M2Y1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDExMVQwMjU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTEwNGZiNGY4MTkwMDYzMmY1MGZmOTM3OTRkMzExOGM2NWIyYWQ5Zjc5OWUyNDRjNDFjMTM3MmYyMWI4MWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6QfFrzL7ImIq723yeZF8P9kZYm5U3Lb7WhZ49crryVs"> 同小白，遇到了和楼主一样的问题。已经重新登陆并更新config的Uid和Cid配置，仍旧提示nga 返回代码不为0: 46 访客不能直接访问
> > > 
> > > 
> > > [@AlarmP4](https://github.com/AlarmP4) 请提供一下tid号，我这边测试一下
> > 
> 
> [@AlarmP4](https://github.com/AlarmP4) 你好，我这边测了一下，假如uid和cid正确的话，应该确实是可以下载这个帖子了。而且我看你的操作和最新程序的一些限制，程序应该是读取到了你提供的uid和cid。
> 
> 后面可能要麻烦你重新获取并设置一下新的uid和cid。用浏览器的无痕窗口打开并登录nga，在登录完毕后再获取相关的uid和cid值并设置，尝试一下

问题已解决，非常感谢<3
