### ISSUE TITLE
无法正确读取移除了注释的 config.ini

### ISSUE THREAD

**Issue by fengshuo2004** [ludoux/ngapost2md#95]
版本：1.5.2
操作系统：Windows 10

为了自动化爬取一些帖子，我写了个 Python 脚本，在启动时会修改 config.ini 填入 UA 和 cookie。更改后的文件长这样：

```ini
[config]
version = 1.4.0

[network]
base_url = https://bbs.nga.cn
ua = `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0`
ngapassportuid = `12345678`
ngapassportcid = `X9moREDACTEDvkn5REDACTEDc3m2REDACTED99n1`
thread = 2
page_download_limit = 100

[post]
get_ip_location = False
enhance_ori_reply = False
use_local_smile_pic = False
local_smile_pic_path = ../smile/
use_title_as_folder_name = False
use_title_as_md_file_name = False


```

如上，我用的 [configparser](https://docs.python.org/3/library/configparser.html) 库加载配置文件时是直接无视注释的，这样一来 config.ini 就没了注释。运行 ngapost2md.exe 不会报任何配置错误但是获取任何帖子都会得到 `2024/06/16 16:34:58 nga 返回代码不为0: 46` （就是未登录错误）。手动填入 UA 和 cookie 不删除注释就没有这种问题。

谢谢！

**Comment by ludoux** [comment]
好的，有空我研究一下

**Comment by ludoux** [comment]
呃我现在才发现，这个 configparser 是大小写不敏感的，但是我这边是大小写敏感的……你看看你那边能不能修改一下，让它不要改变键的大小写。准确来说就只有 `ngaPassportUid` 和 `ngaPassportCid`，因为这两个是nga的cookie名，我就原样保留了

**Comment by ludoux** [comment]
假如仍有问题欢迎 reopen :)

**Comment by fengshuo2004** [comment]
原来是大小写的问题，我根本没注意到。确实我这边的问题。ConfigParser能保留大小写，就是实现方法有点抽象。总之现在解决了，多谢！
